### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by proweber1** [yii-dream-team/yii2-payeer#1]
Почему к вашему модулю нет документации? Как его использовать то?

**Comment by metalagman** [comment]
Можно изучить код и разобраться, есть похожий компонент для перфект мани,
там есть примеры. Можно заплатить мне денег и я настрою :-)
27 дек. 2015 г. 5:24 PM пользователь "proweber1" notifications@github.com
написал:

**Comment by proweber1** [comment]
Да не, спасибо, я сам кодер, разберусь, просто какой понт вываливать компонент который не документирован совсем? Нафиг он кому нужен? Просто больше других нету... Приходится тратить время на разбор27.12.2015, 14:24, "Alexey Samoylov" notifications@github.com:Можно изучить код и разобраться, есть похожий компонент для перфект мани,

там есть примеры. Можно заплатить мне денег и я настрою :-)

27 дек. 2015 г. 5:24 PM пользователь "proweber1" notifications@github.com

написал:
